name: buildwiththeta

packages:
  - packages/*

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false

ide:
  intellij: true

scripts:
  analyze:
    exec: dart analyze .