name: Bug Report
description: Form to report a bug
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug reporting form! Remember, providing as much detail as possible will make it easier for others to help you resolve the bug. If the bug is not immediately reproducible, it may be necessary to provide more context or a sample code snippet that demonstrates the issue. 
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: What were you using when you faced the problem?
      options:
        - Theta Studio
        - Theta Flutter Library
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug
      description: Describe the issue you are encountering. Be as detailed as possible, explaining the steps leading to the bug, and what you expected to happen instead.
      placeholder: I faced this specific bug!
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Flutter Environment
      description: Provide information about your Flutter environment by running the command flutter doctor -v and pasting the output here. If not applicable, write “N/A” or “Not Applicable”
      placeholder: This is my Flutter environment
    validations:
      required: true
  - type: textarea
    id: device
    attributes:
      label: Device Information
      description: Provide specifications about the device on which you are experiencing this issue (e.g., manufacturer, model, OS version, browser used).
      placeholder: These are the specifications of my device
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a set of steps to reproduce the bug. Be as detailed as possible.
      placeholder: 1. ...
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: What were you expecting to happen when you performed the steps above?
      placeholder: I expected this specific output.
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour
      description: What actually happened when you performed the steps above?
      placeholder: I got this output.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Run flutter run or flutter build and paste any error logs that might help understand the issue. If the error log is too long, consider using a service like Gist to provide the link to the log. If not applicable, write "N/A" or "Not applicable".
      placeholder: This is my log.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here. This could include any relevant configuration, add-ons or libraries used, or other details that might help the developers understand the issue.
      placeholder: This is some more additional context about what happened in my project.
    validations:
      required: false
  - type: textarea
    id: possible-solution
    attributes:
      label: Additional Context
      description: If you have an idea of a potential solution, describe it here. If not, feel free to skip this part.
      placeholder: This is my possibile solution to the issue faced.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. Screenshots can be extremely helpful for understanding the issue, especially in the context of visual bugs.
      placeholder: Upload your screenshot just by dragging it
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/buildwiththeta/buildwiththeta/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow the Code of Conduct for this project.
          required: true
