/// [ActionType] identifies which type action will be used
// ignore_for_file: public_member_api_docs

enum ActionType {
  airtable,
  navigation,
  state,
  shopify,
  theme,
  revenueCat,
  qonversion,
  mixpanel,
  firebase,
  firebaseFirestore,
  firebaseStorage,
  supabaseAuth,
  supabaseDatabase,
  supabaseFunctions,
  supabaseStorage,
  camera,
  audioPlayer,
  webview,
  map,
  googleMaps,
  tetaDatabase,
  tetaAuth,
  tetaStore,
  customHttpRequest,
  customFunctions,
  braintree,
  translator,
  apiCalls,
  firebaseAnalytics,
  firebaseMessages,
  alert
}
