name: theta_rendering
description: Rendering package for Theta

version: 0.1.3

repository: https://github.com/buildwiththeta/buildwiththeta
homepage: https://buildwiththeta.com
issue_tracker: https://github.com/buildwiththeta/buildwiththeta/issues
documentation: https://docs.page/buildwiththeta/buildwiththeta

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 

  theta_models: ^0.2.2
  light_logger: ^0.0.3
  collection: ^1.17.1

dependency_overrides:
  theta_models:
    path: ../models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

