name: theta_rendering
description: Rendering package for Theta

version: 0.2.3

repository: https://github.com/buildwiththeta/buildwiththeta
homepage: https://buildwiththeta.com
issue_tracker: https://github.com/buildwiththeta/buildwiththeta/issues
documentation: https://docs.page/buildwiththeta/buildwiththeta

scripts:
  pubget: "flutter pub get"
  dryrun: "dart pub publish --dry-run"
  publish: "dart pub publish"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies: 

  theta_models: ^0.7.2
  light_logger: ^0.0.3
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

