name: example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
scripts: 
  run: flutter run -d chrome
environment: 
  sdk: ">=3.0.0 <4.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  theta: 
    path: ../
dependency_overrides: 
  theta_models: 
    path: ../../models
  theta_open_widgets: 
    path: ../../widgets
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/theta_assets/
