typedef ProjectID = String;
typedef UserID = String;
typedef ChannelID = String;
typedef TeamID = String;
typedef PageID = String;
typedef NodeID = String;
typedef ID = String;
typedef DefaultNodeAttributes = Map<String, dynamic>;
typedef NodeAttributes = Map<String, dynamic>;
