import 'package:theta_models/theta_models.dart';

typedef ProjectID = String;
typedef UserID = String;
typedef BranchID = String;
typedef TeamID = String;
typedef PageID = String;
typedef NodeID = String;
typedef ID = String;
typedef BranchActionLogID = String;
typedef BranchJsonLogID = String;
typedef AssetID = String;
typedef DefaultNodeAttributes = Map<String, dynamic>;
typedef NodeAttributes = Map<String, dynamic>;
typedef Variables = List<VariableEntity>;
typedef ColorStyles = List<ColorStyleEntity>;
typedef TextStyles = List<TextStyleEntity>;
typedef Nodes = List<CNode>;
typedef Pages = List<PageEntity>;
typedef Branches = List<BranchEntity>;
typedef BranchActionLogs = List<BranchActionLogEntity>;
typedef BranchJsonLogs = List<BranchJsonLogEntity>;
typedef Assets = List<AssetEntity>;
