// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:meta/meta.dart' as prefix33;
import 'package:theta_models/src/widgets/dynamic_attributes_parse.dart'
    as prefix0;
import 'package:theta_models/src/widgets/features/align.dart' as prefix1;
import 'package:theta_models/src/widgets/features/blend_mode.dart' as prefix2;
import 'package:theta_models/src/widgets/features/border.dart' as prefix3;
import 'package:theta_models/src/widgets/features/border_radius.dart'
    as prefix4;
import 'package:theta_models/src/widgets/features/border_style.dart' as prefix5;
import 'package:theta_models/src/widgets/features/box_fit.dart' as prefix6;
import 'package:theta_models/src/widgets/features/condition_type.dart'
    as prefix7;
import 'package:theta_models/src/widgets/features/cross_axis_alignment.dart'
    as prefix8;
import 'package:theta_models/src/widgets/features/fill.dart' as prefix9;
import 'package:theta_models/src/widgets/features/font_size.dart' as prefix10;
import 'package:theta_models/src/widgets/features/font_style.dart' as prefix11;
import 'package:theta_models/src/widgets/features/font_weight.dart' as prefix12;
import 'package:theta_models/src/widgets/features/icon_type.dart' as prefix13;
import 'package:theta_models/src/widgets/features/image_type.dart' as prefix14;
import 'package:theta_models/src/widgets/features/keyboard_type.dart'
    as prefix15;
import 'package:theta_models/src/widgets/features/main_axis_alignment.dart'
    as prefix16;
import 'package:theta_models/src/widgets/features/main_axis_size.dart'
    as prefix17;
import 'package:theta_models/src/widgets/features/margins.dart' as prefix18;
import 'package:theta_models/src/widgets/features/shadow.dart' as prefix19;
import 'package:theta_models/src/widgets/features/sizes.dart' as prefix20;
import 'package:theta_models/src/widgets/features/text_align.dart' as prefix21;
import 'package:theta_models/src/widgets/features/text_decoration.dart'
    as prefix22;
import 'package:theta_models/src/widgets/features/text_direction.dart'
    as prefix23;
import 'package:theta_models/src/widgets/features/text_style.dart' as prefix24;
import 'package:theta_models/src/widgets/features/text_type_input.dart'
    as prefix25;
import 'package:theta_models/src/widgets/intrinsic_states/classes.dart'
    as prefix27;
import 'package:theta_models/src/widgets/intrinsic_states/intrinsic_state_parse.dart'
    as prefix26;
import 'package:theta_models/src/widgets/nodes/key_constants.dart' as prefix34;
import 'package:theta_models/src/widgets/nodes/node_type.dart' as prefix35;
import 'package:theta_open_widgets/src/reflectable/adaptors/widget_adapter_annotation.dart'
    as prefix28;
import 'package:theta_open_widgets/src/reflectable/adaptors/widget_adaptors.dart'
    as prefix29;
import 'package:theta_open_widgets/src/reflectable/default_attributes/default_attributes_annotation.dart'
    as prefix30;
import 'package:theta_open_widgets/src/reflectable/default_attributes/default_attributes_classes.dart'
    as prefix31;
import 'package:theta_open_widgets/src/reflectable/nodes/nodes_parse.dart'
    as prefix32;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.DynamicAttributeReflector(): r.ReflectorData(<m.TypeMirror>[],
      null, null, <Type>[prefix0.DynamicAttributes], 1, {}, {}, null, []),
  const prefix0.DynamicAttributeKey(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'FAlign',
            r'.FAlign',
            134217735,
            0,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {
              r'fromJson': () => prefix1.FAlign.fromJson,
              r'convertJsonToValue': () => prefix1.FAlign.convertJsonToValue,
              r'convertDropDownToValue': () =>
                  prefix1.FAlign.convertDropDownToValue,
              r'convertValueToDropDown': () =>
                  prefix1.FAlign.convertValueToDropDown,
              r'convertValueToJson': () => prefix1.FAlign.convertValueToJson,
              r'convertValueToCode': () => prefix1.FAlign.convertValueToCode,
              r'dropdownList': () => prefix1.FAlign.dropdownList
            },
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.align)
            ],
            {
              r'fromJson': 0,
              r'convertJsonToValue': 0,
              r'convertDropDownToValue': 0,
              r'convertValueToDropDown': 0,
              r'convertValueToJson': 0,
              r'convertValueToCode': 0,
              r'dropdownList': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'FBlendMode',
            r'.FBlendMode',
            134217735,
            1,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix2.FBlendMode.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.blendMode)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FBorder',
            r'.FBorder',
            134217735,
            2,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix3.FBorder.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.borders),
              const prefix0.AttributeKey(prefix34.DBKeys.activeBorders)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FBorderRadius',
            r'.FBorderRadius',
            134217735,
            3,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix4.FBorderRadius.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.borderRadius),
              const prefix0.AttributeKey(prefix34.DBKeys.borderRadiusTwo)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FBorderStyle',
            r'.FBorderStyle',
            134217735,
            4,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix5.FBorderStyle.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.borderStyle)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FBoxFit',
            r'.FBoxFit',
            134217735,
            5,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix6.FBoxFit.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.boxFit)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FConditionType',
            r'.FConditionType',
            134217735,
            6,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix7.FConditionType.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.conditionType)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FCrossAxisAlignment',
            r'.FCrossAxisAlignment',
            134217735,
            7,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix8.FCrossAxisAlignment.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.crossAxisAlignment)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FFill',
            r'.FFill',
            134217735,
            8,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {
              r'fromJson': () => prefix9.FFill.fromJson,
              r'alignFromJson': () => prefix9.FFill.alignFromJson,
              r'toCode': () => prefix9.FFill.toCode,
              r'toCodeTests': () => prefix9.FFill.toCodeTests
            },
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.bgFill),
              const prefix0.AttributeKey(prefix34.DBKeys.bgTwoFill),
              const prefix0.AttributeKey(prefix34.DBKeys.textFill),
              const prefix0.AttributeKey(prefix34.DBKeys.activeFill),
              const prefix0.AttributeKey(prefix34.DBKeys.borderFill),
              const prefix0.AttributeKey(prefix34.DBKeys.enabledBorderColor),
              const prefix0.AttributeKey(prefix34.DBKeys.focusedBorderColor),
              const prefix0.AttributeKey(prefix34.DBKeys.cursorColor),
              const prefix0.AttributeKey(prefix34.DBKeys.hintTextColor),
              const prefix0.AttributeKey(prefix34.DBKeys.fill),
              const prefix0.AttributeKey(prefix34.DBKeys.fill2),
              const prefix0.AttributeKey(prefix34.DBKeys.fill3)
            ],
            {
              r'fromJson': 0,
              r'alignFromJson': 2,
              r'toCode': 3,
              r'toCodeTests': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'FFontSize',
            r'.FFontSize',
            134217735,
            9,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix10.FFontSize.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.fontSize)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FFontStyle',
            r'.FFontStyle',
            134217735,
            10,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix11.FFontStyle.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.fontStyle)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FFontWeight',
            r'.FFontWeight',
            134217735,
            11,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {
              r'convertDropDownToValue': () =>
                  prefix12.FFontWeight.convertDropDownToValue,
              r'fromJson': () => prefix12.FFontWeight.fromJson,
              r'getListDropDown': () => prefix12.FFontWeight.getListDropDown
            },
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.fontWeight)
            ],
            {
              r'convertDropDownToValue': 0,
              r'fromJson': 0,
              r'getListDropDown': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'FIconType',
            r'.FIconType',
            134217735,
            12,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix13.FIconType.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.iconType)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FImageType',
            r'.FImageType',
            134217735,
            13,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix14.FImageType.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.imageType)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FKeyboardType',
            r'.FKeyboardType',
            134217735,
            14,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix15.FKeyboardType.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.keyboardType),
              prefix33.immutable
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FMainAxisAlignment',
            r'.FMainAxisAlignment',
            134217735,
            15,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix16.FMainAxisAlignment.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.mainAxisAlignment)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FMainAxisSize',
            r'.FMainAxisSize',
            134217735,
            16,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix17.FMainAxisSize.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.mainAxisSize)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FMargins',
            r'.FMargins',
            134217735,
            17,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {
              r'fromJson': () => prefix18.FMargins.fromJson,
              r'convertToCode': () => prefix18.FMargins.convertToCode
            },
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.margins),
              const prefix0.AttributeKey(prefix34.DBKeys.padding)
            ],
            {r'fromJson': 0, r'convertToCode': 0}),
        r.NonGenericClassMirrorImpl(
            r'FShadow',
            r'.FShadow',
            134217735,
            18,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix19.FShadow.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.shadows)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FSize',
            r'.FSize',
            134217735,
            19,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {
              r'ready': () => prefix20.FSize.ready,
              r'fromJson': () => prefix20.FSize.fromJson,
              r'convertListToCode': () => prefix20.FSize.convertListToCode,
              r'convertTypeToCode': () => prefix20.FSize.convertTypeToCode
            },
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.width),
              const prefix0.AttributeKey(prefix34.DBKeys.widthFactor),
              const prefix0.AttributeKey(prefix34.DBKeys.minWidth),
              const prefix0.AttributeKey(prefix34.DBKeys.maxWidth),
              const prefix0.AttributeKey(prefix34.DBKeys.mainAxisExtend),
              const prefix0.AttributeKey(prefix34.DBKeys.crossAxisExtend),
              const prefix0.AttributeKey(prefix34.DBKeys.height),
              const prefix0.AttributeKey(prefix34.DBKeys.heightFactor),
              const prefix0.AttributeKey(prefix34.DBKeys.minHeight),
              const prefix0.AttributeKey(prefix34.DBKeys.maxHeight)
            ],
            {
              r'ready': 1,
              r'fromJson': 0,
              r'convertListToCode': 0,
              r'convertTypeToCode': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'FTextAlign',
            r'.FTextAlign',
            134217735,
            20,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix21.FTextAlign.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.textAlign)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FTextDecoration',
            r'.FTextDecoration',
            134217735,
            21,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix22.FTextDecoration.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.textDecoration)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FTextDirection',
            r'.FTextDirection',
            134217735,
            22,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix23.FTextDirection.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix33.immutable,
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.textDirection)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FTextStyle',
            r'.FTextStyle',
            134217735,
            23,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix24.FTextStyle.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.textStyle),
              const prefix0.AttributeKey(prefix34.DBKeys.textStyle2)
            ],
            {r'fromJson': 0}),
        r.NonGenericClassMirrorImpl(
            r'FTextTypeInput',
            r'.FTextTypeInput',
            134217735,
            24,
            const prefix0.DynamicAttributeKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {r'fromJson': () => prefix25.FTextTypeInput.fromJson},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix0.dynamicAttributeKey,
              const prefix0.AttributeKey(prefix34.DBKeys.actionValue),
              const prefix0.AttributeKey(prefix34.DBKeys.image),
              const prefix0.AttributeKey(prefix34.DBKeys.textAlign),
              const prefix0.AttributeKey(prefix34.DBKeys.textDecoration),
              const prefix0.AttributeKey(prefix34.DBKeys.textStyle),
              const prefix0.AttributeKey(prefix34.DBKeys.textStyle2),
              const prefix0.AttributeKey(prefix34.DBKeys.value),
              const prefix0.AttributeKey(prefix34.DBKeys.flexValue),
              const prefix0.AttributeKey(prefix34.DBKeys.rotateX),
              const prefix0.AttributeKey(prefix34.DBKeys.rotateY),
              const prefix0.AttributeKey(prefix34.DBKeys.rotateZ),
              const prefix0.AttributeKey(prefix34.DBKeys.tranX),
              const prefix0.AttributeKey(prefix34.DBKeys.tranY),
              const prefix0.AttributeKey(prefix34.DBKeys.duration),
              const prefix0.AttributeKey(prefix34.DBKeys.valueOfCondition),
              const prefix0.AttributeKey(prefix34.DBKeys.mainAxisSpacing),
              const prefix0.AttributeKey(prefix34.DBKeys.crossAxisCount),
              const prefix0.AttributeKey(prefix34.DBKeys.crossAxisSpacing),
              const prefix0.AttributeKey(prefix34.DBKeys.maxLines),
              const prefix0.AttributeKey(prefix34.DBKeys.minLines),
              const prefix0.AttributeKey(prefix34.DBKeys.maxLenght),
              const prefix0.AttributeKey(prefix34.DBKeys.bordersSize),
              const prefix0.AttributeKey(prefix34.DBKeys.childAspectRatio),
              const prefix0.AttributeKey(prefix34.DBKeys.latitude),
              const prefix0.AttributeKey(prefix34.DBKeys.longitude),
              const prefix0.AttributeKey(prefix34.DBKeys.labelText),
              const prefix0.AttributeKey(prefix34.DBKeys.xRotation),
              const prefix0.AttributeKey(prefix34.DBKeys.yRotation),
              const prefix0.AttributeKey(prefix34.DBKeys.zRotation),
              const prefix0.AttributeKey(prefix34.DBKeys.xOffset),
              const prefix0.AttributeKey(prefix34.DBKeys.yOffset),
              const prefix0.AttributeKey(prefix34.DBKeys.rotation),
              const prefix0.AttributeKey(prefix34.DBKeys.xPerspective),
              const prefix0.AttributeKey(prefix34.DBKeys.yPerspective),
              const prefix0.AttributeKey(prefix34.DBKeys.zPerspective),
              const prefix0.AttributeKey(prefix34.DBKeys.xTranslation),
              const prefix0.AttributeKey(prefix34.DBKeys.yTranslation),
              const prefix0.AttributeKey(prefix34.DBKeys.selectedItemName)
            ],
            {r'fromJson': 0})
      ],
      null,
      null,
      <Type>[
        prefix1.FAlign,
        prefix2.FBlendMode,
        prefix3.FBorder,
        prefix4.FBorderRadius,
        prefix5.FBorderStyle,
        prefix6.FBoxFit,
        prefix7.FConditionType,
        prefix8.FCrossAxisAlignment,
        prefix9.FFill,
        prefix10.FFontSize,
        prefix11.FFontStyle,
        prefix12.FFontWeight,
        prefix13.FIconType,
        prefix14.FImageType,
        prefix15.FKeyboardType,
        prefix16.FMainAxisAlignment,
        prefix17.FMainAxisSize,
        prefix18.FMargins,
        prefix19.FShadow,
        prefix20.FSize,
        prefix21.FTextAlign,
        prefix22.FTextDecoration,
        prefix23.FTextDirection,
        prefix24.FTextStyle,
        prefix25.FTextTypeInput
      ],
      25,
      {},
      {},
      null,
      [
        const [1, 0, null],
        const [0, 0, null],
        const [2, 0, null],
        const [
          2,
          0,
          const [#flagConst, #colorStyles]
        ]
      ]),
  const prefix26.NodeTypeISKey(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'AlignIntrinsicStates',
            r'.AlignIntrinsicStates',
            134217735,
            0,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix27.AlignIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.AlignIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.align)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'ButtonIntrinsicStates',
            r'.ButtonIntrinsicStates',
            134217735,
            1,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix27.ButtonIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.ButtonIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.button)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'ColumnIntrinsicStates',
            r'.ColumnIntrinsicStates',
            134217735,
            2,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix27.ColumnIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.ColumnIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.column)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'ComponentIntrinsicStates',
            r'.ComponentIntrinsicStates',
            134217735,
            3,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix27.ComponentIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.ComponentIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.component)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'TeamComponentIntrinsicStates',
            r'.TeamComponentIntrinsicStates',
            134217735,
            4,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix27.TeamComponentIntrinsicStates() : null,
              r'create': (bool b) => () =>
                  b ? prefix27.TeamComponentIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.teamComponent)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'ContainerIntrinsicStates',
            r'.ContainerIntrinsicStates',
            134217735,
            5,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix27.ContainerIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.ContainerIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.container)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'IconIntrinsicStates',
            r'.IconIntrinsicStates',
            134217735,
            6,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix27.IconIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.IconIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.icon)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'ImageIntrinsicStates',
            r'.ImageIntrinsicStates',
            134217735,
            7,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix27.ImageIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.ImageIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.image)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'ListViewIntrinsicStates',
            r'.ListViewIntrinsicStates',
            134217735,
            8,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix27.ListViewIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.ListViewIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.listView),
              const prefix26.NodeKey(prefix35.NType.gridView)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'LottieIntrinsicStates',
            r'.LottieIntrinsicStates',
            134217735,
            9,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix27.LottieIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.LottieIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.lottie)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'RowIntrinsicStates',
            r'.RowIntrinsicStates',
            134217735,
            10,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix27.RowIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.RowIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.row)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'ScaffoldIntrinsicStates',
            r'.ScaffoldIntrinsicStates',
            134217735,
            11,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix27.ScaffoldIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.ScaffoldIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.scaffold)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'StackIntrinsicStates',
            r'.StackIntrinsicStates',
            134217735,
            12,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix27.StackIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.StackIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.stack)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'TextIntrinsicStates',
            r'.TextIntrinsicStates',
            134217735,
            13,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix27.TextIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.TextIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.text)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'TextFieldIntrinsicStates',
            r'.TextFieldIntrinsicStates',
            134217735,
            14,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix27.TextFieldIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.TextFieldIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.textField)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'VideoIntrinsicStates',
            r'.VideoIntrinsicStates',
            134217735,
            15,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix27.VideoIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.VideoIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.video)
            ],
            {}),
        r.NonGenericClassMirrorImpl(
            r'SpacerIntrinsicStates',
            r'.SpacerIntrinsicStates',
            134217735,
            16,
            const prefix26.NodeTypeISKey(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix27.SpacerIntrinsicStates() : null,
              r'create': (bool b) =>
                  () => b ? prefix27.SpacerIntrinsicStates.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix26.nodeTypeISKey,
              const prefix26.NodeKey(prefix35.NType.spacer)
            ],
            {})
      ],
      null,
      null,
      <Type>[
        prefix27.AlignIntrinsicStates,
        prefix27.ButtonIntrinsicStates,
        prefix27.ColumnIntrinsicStates,
        prefix27.ComponentIntrinsicStates,
        prefix27.TeamComponentIntrinsicStates,
        prefix27.ContainerIntrinsicStates,
        prefix27.IconIntrinsicStates,
        prefix27.ImageIntrinsicStates,
        prefix27.ListViewIntrinsicStates,
        prefix27.LottieIntrinsicStates,
        prefix27.RowIntrinsicStates,
        prefix27.ScaffoldIntrinsicStates,
        prefix27.StackIntrinsicStates,
        prefix27.TextIntrinsicStates,
        prefix27.TextFieldIntrinsicStates,
        prefix27.VideoIntrinsicStates,
        prefix27.SpacerIntrinsicStates
      ],
      17,
      {},
      {},
      null,
      [
        const [0, 0, null]
      ]),
  const prefix26.IntrinsicStateReflector(): r.ReflectorData(<m.TypeMirror>[],
      null, null, <Type>[prefix26.DynamicIntrinsicState], 1, {}, {}, null, []),
  const prefix28.DynamicWidgetAdapterReflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'WidgetAdapterParse',
            r'.WidgetAdapterParse',
            134217735,
            0,
            const prefix28.DynamicWidgetAdapterReflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix28.WidgetAdapterParse() : null},
            -1,
            -1,
            const <int>[-1],
            const <Object>[const prefix28.DynamicWidgetAdapterReflector()],
            {
              r'==': 0,
              r'toString': 1,
              r'noSuchMethod': 0,
              r'hashCode': 1,
              r'runtimeType': 1,
              r'getByType': 0
            })
      ],
      null,
      null,
      <Type>[prefix28.WidgetAdapterParse],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'getByType': (dynamic instance) => instance.getByType
      },
      {},
      null,
      [
        const [1, 0, null],
        const [0, 0, null]
      ]),
  const prefix28.DynamicAdapter(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'AlignWidgetAdapter',
            r'.AlignWidgetAdapter',
            134217735,
            0,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.AlignWidgetAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.AlignWidgetAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.align)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'ButtonAdapter',
            r'.ButtonAdapter',
            134217735,
            1,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.ButtonAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.ButtonAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.button)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'ColumnAdapter',
            r'.ColumnAdapter',
            134217735,
            2,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.ColumnAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.ColumnAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.column)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'BoxAdapter',
            r'.BoxAdapter',
            134217735,
            3,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.BoxAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.BoxAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.container)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'GridViewAdapter',
            r'.GridViewAdapter',
            134217735,
            4,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.GridViewAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.GridViewAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.gridView)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'MaterialIconAdapter',
            r'.MaterialIconAdapter',
            134217735,
            5,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.MaterialIconAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.MaterialIconAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.icon)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'ImageAdapter',
            r'.ImageAdapter',
            134217735,
            6,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.ImageAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.ImageAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.image)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'ListViewAdapter',
            r'.ListViewAdapter',
            134217735,
            7,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.ListViewAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.ListViewAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.listView)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'LottieAdapter',
            r'.LottieAdapter',
            134217735,
            8,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.LottieAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.LottieAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.lottie)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'RowAdapter',
            r'.RowAdapter',
            134217735,
            9,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.RowAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.RowAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.row)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'ScaffoldAdapter',
            r'.ScaffoldAdapter',
            134217735,
            10,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.ScaffoldAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.ScaffoldAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.scaffold)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'StackAdapter',
            r'.StackAdapter',
            134217735,
            11,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.StackAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.StackAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.stack)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'TextAdapter',
            r'.TextAdapter',
            134217735,
            12,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.TextAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.TextAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.text)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'TextFieldAdapter',
            r'.TextFieldAdapter',
            134217735,
            13,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.TextFieldAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.TextFieldAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.textField)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'VideoAdapter',
            r'.VideoAdapter',
            134217735,
            14,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.VideoAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.VideoAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.video)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'ComponentAdapter',
            r'.ComponentAdapter',
            134217735,
            15,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.ComponentAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.ComponentAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.component)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'TeamComponentAdapter',
            r'.TeamComponentAdapter',
            134217735,
            16,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.TeamComponentAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.TeamComponentAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.teamComponent)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'SpacerAdapter',
            r'.SpacerAdapter',
            134217735,
            17,
            const prefix28.DynamicAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix29.SpacerAdapter() : null,
              r'create': (bool b) =>
                  () => b ? prefix29.SpacerAdapter.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix28.dynamicAdapter,
              const prefix26.NodeKey(prefix35.NType.spacer)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toWidget': 0
            })
      ],
      null,
      null,
      <Type>[
        prefix29.AlignWidgetAdapter,
        prefix29.ButtonAdapter,
        prefix29.ColumnAdapter,
        prefix29.BoxAdapter,
        prefix29.GridViewAdapter,
        prefix29.MaterialIconAdapter,
        prefix29.ImageAdapter,
        prefix29.ListViewAdapter,
        prefix29.LottieAdapter,
        prefix29.RowAdapter,
        prefix29.ScaffoldAdapter,
        prefix29.StackAdapter,
        prefix29.TextAdapter,
        prefix29.TextFieldAdapter,
        prefix29.VideoAdapter,
        prefix29.ComponentAdapter,
        prefix29.TeamComponentAdapter,
        prefix29.SpacerAdapter
      ],
      18,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toWidget': (dynamic instance) => instance.toWidget
      },
      {},
      null,
      [
        const [
          0,
          0,
          const [#context, #state]
        ],
        const [1, 0, null]
      ]),
  const prefix30.DynamicDefaultAttributeAdapter(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'AlignWidgetDefaultAttributes',
            r'.AlignWidgetDefaultAttributes',
            134217735,
            0,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.AlignWidgetDefaultAttributes() : null,
              r'create': (bool b) => () =>
                  b ? prefix31.AlignWidgetDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.align)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'ButtonDefaultAttributes',
            r'.ButtonDefaultAttributes',
            134217735,
            1,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.ButtonDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.ButtonDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.button)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'FlexDefaultAttributes',
            r'.FlexDefaultAttributes',
            134217735,
            2,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.FlexDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.FlexDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.column),
              const prefix26.NodeKey(prefix35.NType.row)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'ComponentDefaultAttributes',
            r'.ComponentDefaultAttributes',
            134217735,
            3,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.ComponentDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.ComponentDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.component)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'TeamComponentDefaultAttributes',
            r'.TeamComponentDefaultAttributes',
            134217735,
            4,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.TeamComponentDefaultAttributes() : null,
              r'create': (bool b) => () =>
                  b ? prefix31.TeamComponentDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.teamComponent)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'BoxDefaultAttributes',
            r'.BoxDefaultAttributes',
            134217735,
            5,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix31.BoxDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.BoxDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.container),
              const prefix26.NodeKey(prefix35.NType.image)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'IconDefaultAttributes',
            r'.IconDefaultAttributes',
            134217735,
            6,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.IconDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.IconDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.icon)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'ListViewDefaultAttributes',
            r'.ListViewDefaultAttributes',
            134217735,
            7,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.ListViewDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.ListViewDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.listView)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'LottieDefaultAttributes',
            r'.LottieDefaultAttributes',
            134217735,
            8,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.LottieDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.LottieDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.lottie)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'ScaffoldDefaultAttributes',
            r'.ScaffoldDefaultAttributes',
            134217735,
            9,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.ScaffoldDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.ScaffoldDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.scaffold)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'StackDefaultAttributes',
            r'.StackDefaultAttributes',
            134217735,
            10,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.StackDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.StackDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.stack)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'TextDefaultAttributes',
            r'.TextDefaultAttributes',
            134217735,
            11,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.TextDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.TextDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.text)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'TextFieldDefaultAttributes',
            r'.TextFieldDefaultAttributes',
            134217735,
            12,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.TextFieldDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.TextFieldDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.textField)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'VideoDefaultAttributes',
            r'.VideoDefaultAttributes',
            134217735,
            13,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.VideoDefaultAttributes() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.VideoDefaultAttributes.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.video)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'SpacerDefaultAttribute',
            r'.SpacerDefaultAttribute',
            134217735,
            14,
            const prefix30.DynamicDefaultAttributeAdapter(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix31.SpacerDefaultAttribute() : null,
              r'create': (bool b) =>
                  () => b ? prefix31.SpacerDefaultAttribute.create() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix30.dynamicDefaultAttribute,
              const prefix26.NodeKey(prefix35.NType.spacer)
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'get': 0
            })
      ],
      null,
      null,
      <Type>[
        prefix31.AlignWidgetDefaultAttributes,
        prefix31.ButtonDefaultAttributes,
        prefix31.FlexDefaultAttributes,
        prefix31.ComponentDefaultAttributes,
        prefix31.TeamComponentDefaultAttributes,
        prefix31.BoxDefaultAttributes,
        prefix31.IconDefaultAttributes,
        prefix31.ListViewDefaultAttributes,
        prefix31.LottieDefaultAttributes,
        prefix31.ScaffoldDefaultAttributes,
        prefix31.StackDefaultAttributes,
        prefix31.TextDefaultAttributes,
        prefix31.TextFieldDefaultAttributes,
        prefix31.VideoDefaultAttributes,
        prefix31.SpacerDefaultAttribute
      ],
      15,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'get': (dynamic instance) => instance.get
      },
      {},
      null,
      [
        const [0, 0, null],
        const [1, 0, null]
      ]),
  const prefix30.DynamicDefaultAttributesReflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'DefaultAttributesParse',
            r'.DefaultAttributesParse',
            134217735,
            0,
            const prefix30.DynamicDefaultAttributesReflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix30.DefaultAttributesParse() : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[const prefix30.DynamicDefaultAttributesReflector()],
            {
              r'==': 0,
              r'toString': 1,
              r'noSuchMethod': 0,
              r'hashCode': 1,
              r'runtimeType': 1,
              r'getByType': 0
            })
      ],
      null,
      null,
      <Type>[prefix30.DefaultAttributesParse],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'getByType': (dynamic instance) => instance.getByType
      },
      {},
      null,
      [
        const [1, 0, null],
        const [0, 0, null]
      ]),
  const prefix32.NodeDeclarationReflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'NodesParse',
            r'.NodesParse',
            134217735,
            0,
            const prefix32.NodeDeclarationReflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix32.NodesParse() : null},
            -1,
            -1,
            const <int>[-1],
            const <Object>[const prefix32.NodeDeclarationReflector()],
            {})
      ],
      null,
      null,
      <Type>[prefix32.NodesParse],
      1,
      {},
      {},
      null,
      [
        const [0, 0, null]
      ]),
  const prefix32.NodeDeclaration(): r.ReflectorData(
      <m.TypeMirror>[], null, null, <Type>[], 0, {}, {}, null, [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
