name: flutter_riverpod_counter
description: A simple counter app made with Theta and Riverpod. The project it taken from the official example of Riverpod library.

publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  theta: any
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.1.1

dependency_overrides:
  theta:
    path: ../../packages/builder

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  build_verify: ^3.0.0
  custom_lint: ^0.4.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
