name: theta_cli
description: Theta CLI allows developers to interact with and manage the Theta projcts efficiently.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  mason_logger: ^0.2.5
  pub_updater: ^0.3.0
  equatable: ^2.0.3
  either_dart: ^0.4.0
  http: ^1.0.0
  get_it: ^7.6.0
  uuid: ^3.0.7
  path_provider: ^2.0.15

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.2

executables:
  theta:
